# Generated by Django 5.1.2 on 2024-10-11 14:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GameEdition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edition_name', models.CharField(blank=True, max_length=100, null=True)),
                ('release_year', models.PositiveIntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamedata.game')),
            ],
        ),
        migrations.CreateModel(
            name='CharacteristicType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('builder_id', models.CharField(blank=True, max_length=40, null=True)),
                ('abbreviation', models.CharField(max_length=10)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamedata.gameedition')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('builder_id', models.CharField(blank=True, max_length=40, null=True)),
                ('version_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamedata.gameedition')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProfileCharacteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_text', models.TextField(blank=True, null=True)),
                ('characteristic_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamedata.characteristictype')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamedata.profile')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('builder_id', models.CharField(blank=True, max_length=40, null=True)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamedata.gameedition')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamedata.profiletype'),
        ),
        migrations.AddField(
            model_name='characteristictype',
            name='profile_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamedata.profiletype'),
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('builder_id', models.CharField(blank=True, max_length=40, null=True)),
                ('publication_year', models.PositiveIntegerField(blank=True, null=True)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamedata.gameedition')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='publication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gamedata.publication'),
        ),
    ]
