# Generated by Django 5.1.2 on 2024-10-11 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublishedVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.CharField(max_length=10)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('release_year', models.PositiveSmallIntegerField(blank=True, help_text='If exact release date is not known', null=True)),
                ('release_month', models.PositiveSmallIntegerField(blank=True, help_text='If exact release date is not known', null=True)),
                ('sort_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='version_date',
        ),
        migrations.CreateModel(
            name='GameMod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamedata.gameedition')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='document',
            field=models.ForeignKey(blank=True, help_text='The exact publication this version was found in', null=True, on_delete=django.db.models.deletion.CASCADE, to='gamedata.publishedversion'),
        ),
        migrations.CreateModel(
            name='PublishedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamedata.publication')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamedata.publisher')),
            ],
        ),
        migrations.CreateModel(
            name='RawErrata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PublishedDocumentVersion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamedata.publisheddocument')),
            ],
        ),
    ]
